<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PaisesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('paises')->delete();

        \DB::table('paises')->insert(array(
            0 => array('id_pais'=>'es','nombre_pais'=>'España','dificultad_pais'=>1),
            1 => array('id_pais'=>'br','nombre_pais'=>'Brasil','dificultad_pais'=>1),
            2 => array('id_pais'=>'en','nombre_pais'=>'Inglaterra','dificultad_pais'=>1),
            3 => array('id_pais'=>'fr','nombre_pais'=>'Francia','dificultad_pais'=>1),
            4 => array('id_pais'=>'it','nombre_pais'=>'Italia','dificultad_pais'=>1),
            5 => array('id_pais'=>'ar','nombre_pais'=>'Argentina','dificultad_pais'=>1),
            6 => array('id_pais'=>'de','nombre_pais'=>'Alemania','dificultad_pais'=>1),
            7 => array('id_pais'=>'pt','nombre_pais'=>'Portugal','dificultad_pais'=>1),
            8 => array('id_pais'=>'nl','nombre_pais'=>'Países Bajos','dificultad_pais'=>1),

            9 => array('id_pais'=>'be','nombre_pais'=>'Bélgica','dificultad_pais'=>2),
            10 => array('id_pais'=>'uy','nombre_pais'=>'Uruguay','dificultad_pais'=>2),
            11 => array('id_pais'=>'mx','nombre_pais'=>'México','dificultad_pais'=>2),
            12 => array('id_pais'=>'co','nombre_pais'=>'Colombia','dificultad_pais'=>2),
            13 => array('id_pais'=>'hr','nombre_pais'=>'Croacia','dificultad_pais'=>2),
            14 => array('id_pais'=>'dk','nombre_pais'=>'Dinamarca','dificultad_pais'=>2),
            15 => array('id_pais'=>'rs','nombre_pais'=>'Serbia','dificultad_pais'=>2),
            16 => array('id_pais'=>'ch','nombre_pais'=>'Suiza','dificultad_pais'=>2),
            17 => array('id_pais'=>'pl','nombre_pais'=>'Polonia','dificultad_pais'=>2),
            18 => array('id_pais'=>'se','nombre_pais'=>'Suecia','dificultad_pais'=>2),
            19 => array('id_pais'=>'at','nombre_pais'=>'Austria','dificultad_pais'=>2),
            20 => array('id_pais'=>'jp','nombre_pais'=>'Japón','dificultad_pais'=>2),

            21 => array('id_pais'=>'usa','nombre_pais'=>'Estados Unidos','dificultad_pais'=>3),
            22 => array('id_pais'=>'cl','nombre_pais'=>'Chile','dificultad_pais'=>3),
            23 => array('id_pais'=>'türki','nombre_pais'=>'Türkiye','dificultad_pais'=>3),
            24 => array('id_pais'=>'sn','nombre_pais'=>'Senegal','dificultad_pais'=>3),
            25 => array('id_pais'=>'ci','nombre_pais'=>'Costa de Marfil','dificultad_pais'=>3),
            26 => array('id_pais'=>'ma','nombre_pais'=>'Marruecos','dificultad_pais'=>3),
            27 => array('id_pais'=>'ng','nombre_pais'=>'Nigeria','dificultad_pais'=>3),
            28 => array('id_pais'=>'gh','nombre_pais'=>'Ghana','dificultad_pais'=>3),
            29 => array('id_pais'=>'sco','nombre_pais'=>'Escocia','dificultad_pais'=>3),
            30 => array('id_pais'=>'gr','nombre_pais'=>'Grecia','dificultad_pais'=>3),
            31 => array('id_pais'=>'dz','nombre_pais'=>'Argelia','dificultad_pais'=>3),
            32 => array('id_pais'=>'cm','nombre_pais'=>'Camerún','dificultad_pais'=>3),
            33 => array('id_pais'=>'ie','nombre_pais'=>'Irlanda','dificultad_pais'=>3),
            34 => array('id_pais'=>'cd','nombre_pais'=>'República Democrática del Congo','dificultad_pais'=>3),
            35 => array('id_pais'=>'cz','nombre_pais'=>'República Checa','dificultad_pais'=>3),
            36 => array('id_pais'=>'no','nombre_pais'=>'Noruega','dificultad_pais'=>3),

            // Dificultad 4
            37 => array('id_pais'=>'py','nombre_pais'=>'Paraguay','dificultad_pais'=>4),
            38 => array('id_pais'=>'ml','nombre_pais'=>'Malí','dificultad_pais'=>4),
            39 => array('id_pais'=>'ec','nombre_pais'=>'Ecuador','dificultad_pais'=>4),
            40 => array('id_pais'=>'wls','nombre_pais'=>'Gales','dificultad_pais'=>4),
            41 => array('id_pais'=>'ca','nombre_pais'=>'Canadá','dificultad_pais'=>4),
            42 => array('id_pais'=>'sk','nombre_pais'=>'Eslovaquia','dificultad_pais'=>4),
            43 => array('id_pais'=>'ua','nombre_pais'=>'Ucrania','dificultad_pais'=>4),
            44 => array('id_pais'=>'ve','nombre_pais'=>'Venezuela','dificultad_pais'=>4),
            45 => array('id_pais'=>'si','nombre_pais'=>'Eslovenia','dificultad_pais'=>4),
            46 => array('id_pais'=>'ba','nombre_pais'=>'Bosnia y Herzegovina','dificultad_pais'=>4),
            47 => array('id_pais'=>'ro','nombre_pais'=>'Rumanía','dificultad_pais'=>4),
            48 => array('id_pais'=>'gn','nombre_pais'=>'Guinea','dificultad_pais'=>4),
            49 => array('id_pais'=>'jm','nombre_pais'=>'Jamaica','dificultad_pais'=>4),
            50 => array('id_pais'=>'ru','nombre_pais'=>'Rusia','dificultad_pais'=>4),
            51 => array('id_pais'=>'kr','nombre_pais'=>'Corea del Sur','dificultad_pais'=>4),
            52 => array('id_pais'=>'hu','nombre_pais'=>'Hungría','dificultad_pais'=>4),
            53 => array('id_pais'=>'al','nombre_pais'=>'Albania','dificultad_pais'=>4),
            54 => array('id_pais'=>'xk','nombre_pais'=>'Kosovo','dificultad_pais'=>4),
            55 => array('id_pais'=>'ao','nombre_pais'=>'Angola','dificultad_pais'=>4),
            56 => array('id_pais'=>'nir','nombre_pais'=>'Irlanda del Norte','dificultad_pais'=>4),
            57 => array('id_pais'=>'cv','nombre_pais'=>'Cabo Verde','dificultad_pais'=>4),
            58 => array('id_pais'=>'pe','nombre_pais'=>'Perú','dificultad_pais'=>4),
            59 => array('id_pais'=>'is','nombre_pais'=>'Islandia','dificultad_pais'=>4),
            60 => array('id_pais'=>'au','nombre_pais'=>'Australia','dificultad_pais'=>4),
            61 => array('id_pais'=>'gw','nombre_pais'=>'Guinea-Bisáu','dificultad_pais'=>4),
            62 => array('id_pais'=>'cw','nombre_pais'=>'Curazao','dificultad_pais'=>4),
            63 => array('id_pais'=>'bf','nombre_pais'=>'Burkina Faso','dificultad_pais'=>4),
            64 => array('id_pais'=>'fi','nombre_pais'=>'Finlandia','dificultad_pais'=>4),
            65 => array('id_pais'=>'eg','nombre_pais'=>'Egipto','dificultad_pais'=>4),
            66 => array('id_pais'=>'mk','nombre_pais'=>'Macedonia del Norte','dificultad_pais'=>4),
            67 => array('id_pais'=>'tn','nombre_pais'=>'Túnez','dificultad_pais'=>4),
            68 => array('id_pais'=>'tg','nombre_pais'=>'Togo','dificultad_pais'=>4),
            69 => array('id_pais'=>'gm','nombre_pais'=>'Gambia','dificultad_pais'=>4),
            70 => array('id_pais'=>'sr','nombre_pais'=>'Surinam','dificultad_pais'=>4),
            71 => array('id_pais'=>'hn','nombre_pais'=>'Honduras','dificultad_pais'=>4),
            72 => array('id_pais'=>'gp','nombre_pais'=>'Guadalupe','dificultad_pais'=>4),
            73 => array('id_pais'=>'cr','nombre_pais'=>'Costa Rica','dificultad_pais'=>4),
            74 => array('id_pais'=>'me','nombre_pais'=>'Montenegro','dificultad_pais'=>4),
            75 => array('id_pais'=>'za','nombre_pais'=>'Sudáfrica','dificultad_pais'=>4),
            76 => array('id_pais'=>'ge','nombre_pais'=>'Georgia','dificultad_pais'=>4),
            77 => array('id_pais'=>'ir','nombre_pais'=>'Irán','dificultad_pais'=>4),
            78 => array('id_pais'=>'mq','nombre_pais'=>'Martinica','dificultad_pais'=>4),
            79 => array('id_pais'=>'bg','nombre_pais'=>'Bulgaria','dificultad_pais'=>4),
            80 => array('id_pais'=>'zw','nombre_pais'=>'Zimbabue','dificultad_pais'=>4),
            81 => array('id_pais'=>'il','nombre_pais'=>'Israel','dificultad_pais'=>4),
            82 => array('id_pais'=>'do','nombre_pais'=>'República Dominicana','dificultad_pais'=>4),
            83 => array('id_pais'=>'gq','nombre_pais'=>'Guinea Ecuatorial','dificultad_pais'=>4),
            84 => array('id_pais'=>'cn','nombre_pais'=>'China','dificultad_pais'=>4),
            85 => array('id_pais'=>'sl','nombre_pais'=>'Sierra Leona','dificultad_pais'=>4),
            86 => array('id_pais'=>'qa','nombre_pais'=>'Catar','dificultad_pais'=>4),
            87 => array('id_pais'=>'nz','nombre_pais'=>'Nueva Zelanda','dificultad_pais'=>4),
            88 => array('id_pais'=>'ga','nombre_pais'=>'Gabón','dificultad_pais'=>4),
            89 => array('id_pais'=>'id','nombre_pais'=>'Indonesia','dificultad_pais'=>4),
            90 => array('id_pais'=>'bi','nombre_pais'=>'Burundi','dificultad_pais'=>4),
            91 => array('id_pais'=>'cg','nombre_pais'=>'Congo','dificultad_pais'=>4),
            92 => array('id_pais'=>'iq','nombre_pais'=>'Irak','dificultad_pais'=>4),
            93 => array('id_pais'=>'bj','nombre_pais'=>'Benín','dificultad_pais'=>4),
            94 => array('id_pais'=>'am','nombre_pais'=>'Armenia','dificultad_pais'=>4),
            95 => array('id_pais'=>'km','nombre_pais'=>'Comoras','dificultad_pais'=>4),
            96 => array('id_pais'=>'pa','nombre_pais'=>'Panamá','dificultad_pais'=>4),
            97 => array('id_pais'=>'uz','nombre_pais'=>'Uzbekistán','dificultad_pais'=>4),
            98 => array('id_pais'=>'mg','nombre_pais'=>'Madagascar','dificultad_pais'=>4),
            99 => array('id_pais'=>'lu','nombre_pais'=>'Luxemburgo','dificultad_pais'=>4),
            100 => array('id_pais'=>'md','nombre_pais'=>'Moldavia','dificultad_pais'=>4),
            101 => array('id_pais'=>'mz','nombre_pais'=>'Mozambique','dificultad_pais'=>4),
            102 => array('id_pais'=>'ht','nombre_pais'=>'Haití','dificultad_pais'=>4),
            103 => array('id_pais'=>'zm','nombre_pais'=>'Zambia','dificultad_pais'=>4),
            104 => array('id_pais'=>'jo','nombre_pais'=>'Jordania','dificultad_pais'=>4),
            105 => array('id_pais'=>'ee','nombre_pais'=>'Estonia','dificultad_pais'=>4),
            106 => array('id_pais'=>'gt','nombre_pais'=>'Guatemala','dificultad_pais'=>4),
            107 => array('id_pais'=>'td','nombre_pais'=>'Chad','dificultad_pais'=>4),
            108 => array('id_pais'=>'by','nombre_pais'=>'Bielorrusia','dificultad_pais'=>4),
            109 => array('id_pais'=>'cf','nombre_pais'=>'República Centroafricana','dificultad_pais'=>4),
            110 => array('id_pais'=>'gd','nombre_pais'=>'Granada','dificultad_pais'=>4),
            111 => array('id_pais'=>'ph','nombre_pais'=>'Filipinas','dificultad_pais'=>4),
            112 => array('id_pais'=>'lt','nombre_pais'=>'Lituania','dificultad_pais'=>4),
            113 => array('id_pais'=>'ke','nombre_pais'=>'Kenia','dificultad_pais'=>4),
            114 => array('id_pais'=>'kz','nombre_pais'=>'Kazajistán','dificultad_pais'=>4),
            115 => array('id_pais'=>'mt','nombre_pais'=>'Malta','dificultad_pais'=>4),
            116 => array('id_pais'=>'my','nombre_pais'=>'Malasia','dificultad_pais'=>4),
            117 => array('id_pais'=>'mu','nombre_pais'=>'Mauricio','dificultad_pais'=>4),
            118 => array('id_pais'=>'mr','nombre_pais'=>'Mauritania','dificultad_pais'=>4),
            119 => array('id_pais'=>'ly','nombre_pais'=>'Libia','dificultad_pais'=>4),
            120 => array('id_pais'=>'kn','nombre_pais'=>'San Cristóbal y Nieves','dificultad_pais'=>4),
            121 => array('id_pais'=>'sa','nombre_pais'=>'Arabia Saudí','dificultad_pais'=>4),
            122 => array('id_pais'=>'saint','nombre_pais'=>'Saint-Martin','dificultad_pais'=>4),
            123 => array('id_pais'=>'tt','nombre_pais'=>'Trinidad y Tobago','dificultad_pais'=>4),
            124 => array('id_pais'=>'sy','nombre_pais'=>'Siria','dificultad_pais'=>4),
            125 => array('id_pais'=>'tz','nombre_pais'=>'Tanzania','dificultad_pais'=>4),
            126 => array('id_pais'=>'ae','nombre_pais'=>'Emiratos Árabes Unidos','dificultad_pais'=>4),
        ));
    }
}
